### ISSUE TITLE
Add functionality for cache management - `Get-BicepCache` & `Clear-BicepCache`

### ISSUE THREAD

**Issue by bjompen** [PSBicep/PSBicep#234]
**Is your feature request related to a problem? Please describe.**
Since we have functionality for downloading modules to cache maybe we should look in to the possibility of adding cache management functionality?

**Some  suggestions**
- Get-PSBicepCache
  - Show what modules are currently cached, including versions
- Clear-PSBicepCache
  - Clear entire cache, or if possible, remove unique modules
- Verify-PSBicepCache
  - Is my cached package(s) up to date

I don't know if any of this is even possible today, but is it worth researching?

**Comment by PalmEmanuel** [comment]
I think we could remove the PS* part of the commands, but I like the idea!

**Comment by StefanIvemo** [comment]
> I think we could remove the PS* part of the commands, but I like the idea!

I agree!

@bjompen great ieda!

**Comment by StefanIvemo** [comment]
Will be hard to verify the cache since it requires authentication and you could have modules cached from a bunch of different ACRs in different tenants. Could work if you always specify which registry to verify against. 
`Verify-BicepCache -Registry mymodules.azurecr.io`

**Comment by PalmEmanuel** [comment]
I don't think `Verify-BicepCache` will be possible / useful. Even if we could potentially list all possible modules uploaded, there is no way for us to know which the latest one is since there is no enforced standard on tags. If we take a look at the format for a second we'll see why:
```
br:psbicepexample.azurecr.io/modules/recoveryservicesvault:v1
```
We could of course try to parse it and attempt to see if there is a `v2` tag available, but what do we look for if it's called `september06-staging` or something completely different from what we would expect? I think it's bound to fail, since the format itself is not always used for versioning in the traditional number sense. Unless it's enforced, it'll be hard to check. The rest of the problem is already solved by `Restore-Bicep` to download the latest registry artifacts (modules).

On that note, I think a `Get-BicepCache` could be very cool, and `Clear-BicepCache` as well (even though it should realistically just do something like `Get-BicepCache | Remove-Item`. With `Get-BicepCache` we could potentially even see if there are other tags available, something like `Get-BicepCache -ListAvailable`!

**Comment by StefanIvemo** [comment]
> We could of course try to parse it and attempt to see if there is a `v2` tag available, but what do we look for if it's called `september06-staging` or something completely different from what we would expect? I think it's bound to fail, since the format itself is not always used for versioning in the traditional number sense. Unless it's enforced, it'll be hard to check. The rest of the problem is already solved by `Restore-Bicep` to download the latest registry artifacts (modules).

There is no use to look for a v2 if it's not beeing referenced by any template. Bicep will only cache modules from the registry used in templates. The language server will restore the module to the cache as soon as I reference it in my template when authoring in VSCode. A build will also always automatically try to restore the modules. We can skip the `Verify-BicepCache` command.

I like the idea of `Clear-BicepCache` even though I could use `Get-BicepCache | Remove-Item`. We know that the cache is saved to the local file system and that we can pipe it to `Remove-Item` but it might not be obvious for our users. 

```powershell
# Clear all cached modules from bicep registries
Clear-BicepCache -Type BicepRegistry

# Clear all cached modules from template specs
Clear-BicepCache -Type TemplateSpecs

# Clear all cached modules for a specific registry
Clear-BicepCache -Registry bicepmodules.azurecr.io

# Clear Clear all cached modules for a specific registry and repository
Clear-BicepCache -Registry bicepmodules.azurecr.io -Repository bicep/storage

Und so weiter...
```
