### ISSUE TITLE
'metadata description = ''' generates an error BCP059

### ISSUE THREAD

**Issue by BertusV** [PSBicep/PSBicep#314]
**Describe the bug**
Module level  "metadata description " generate an error in Build-Bicep.

**To Reproduce**
1. Add:  metadata description = 'My description' to a bicep file.
2. run Build-Bicep on the bicep [file]()
3. error:   BCP059: The name "description" is not a function.

**Expected behavior**
For the Bicep file to build the same way as: Az Bicep build.

**Additional context**
None.

<img width="774" alt="image" src="https://github.com/PSBicep/PSBicep/assets/8254703/4bb1a3c3-796f-4c44-9874-29bbe8b77708">

**Comment by StefanIvemo** [comment]
Thanks for reporting this. This is an issue since the latest release of the Bicep module is using an older Bicep version where this was a bug. We are working on shipping a new release that are using newer Bicep assemblies. In the meanwhile using the pre-release version of the module will solve this.

`Install-Module -Name Bicep -AllowPrerelease`

**Comment by BertusV** [comment]
Thanks Stafan.

**Comment by SimonWahlin** [comment]
This should be fixed in version 2.4.0.
Closing
